spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/openapi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  type-aliases-package: com.example.openplatform.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名规则映射
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
shiro:
  loginUrl: /login.html
  web:
    enabled: true

